image: registry-gitlab.pasteur.fr/bia/icy/gitlab-ci:v1.0.0

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - when: never

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: '-Dargline="Xmx1024m" -Dmaven.repo.local=.m2/repository'

stages:
  - build
#  - release
  - deploy-snapshot
  - deploy-release

cache:
  paths:
    - .m2/repository
    - target/

build-job:
  stage: build
  script:
    - echo "Building artifact…"
    - mvn -X $MAVEN_CLI_OPTS clean install
  artifacts:
    when: on_success
    expire_in: 1 hour
    paths:
      - target/

#release-job:
#  stage: release
#  dependencies:
#    - test-job
#  script:
#    - echo "Creating release…"
#  rules:
#    - if: $CI_COMMIT_TAG =~ /^v(\d+\.\d+\.\d+)(-(a|b|rc)(.\d+)?)?$/
#      when: on_success
#  release:
#    tag_name: '$CI_COMMIT_TAG'
#    description: '$CI_COMMIT_TAG_MESSAGE'

deploy-snapshot-job:
  stage: deploy-snapshot
  dependencies:
    - build-job
  before_script:
    - echo "Checking SNAPSHOT presence…"
    - export JAR_VERSION=$(cat pom.xml | sed '2 s/xmlns=".*"//g' | xmllint --xpath 'string(//project/version)' -)
    - if ! [[ $JAR_VERSION =~ .*SNAPSHOT ]]; then >&2 echo "Unable to deploy artifact, the project is not a SNAPSHOT"; exit 0; fi
  script:
    - echo "Deploying artifact…"
#    - mvn -X $MAVEN_CLI_OPTS deploy
  artifacts:
    when: on_success
    expire_in: 1 hour
    paths:
      - target/*.jar
  rules:
    - if: $CI_COMMIT_TAG !~ /^v(\d+\.\d+\.\d+)(-(a|b|rc)(.\d+)?)?$/
      when: manual

deploy-release-job:
  stage: deploy-release
  dependencies:
    - build-job
  before_script:
    - echo "Checking POM file…"
    - export JAR_VERSION=$(cat pom.xml | sed '2 s/xmlns=".*"//g' | xmllint --xpath 'string(//project/version)' -)
    - if [[ $JAR_VERSION =~ .*SNAPSHOT ]]; then echo "Unable to deploy artifact, the project is a SNAPSHOT"; exit 0; fi
  script:
    - echo "Deploying artifacts…"
#    - mvn -X $MAVEN_CLI_OPTS deploy
  artifacts:
    when: on_success
    expire_in: 1 hour
    paths:
      - target/*.jar
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(\d+\.\d+\.\d+)(-(a|b|rc)(.\d+)?)?$/
      when: manual