<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.scijava</groupId>
        <artifactId>pom-scijava</artifactId>
        <version>44.0.0</version>
    </parent>

    <groupId>fr.icy</groupId>
    <artifactId>pom-icy</artifactId>
    <version>3.0.0-a.8-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>Parent POM base</name>
    <description>Common parent POM for all Icy related projects</description>
    <url>https://icy.bioimageanalysis.org/</url>
    <inceptionYear>2020</inceptionYear>

    <scm>
        <url>https://gitlab.pasteur.fr/bia/icy/pom-icy</url>
        <tag>v${project.version}</tag>
    </scm>

    <issueManagement>
        <system>GitLab Issues</system>
        <url>https://gitlab.pasteur.fr/bia/icy/pom-icy/-/issues</url>
    </issueManagement>
    <ciManagement>
        <system>GitLab CI</system>
        <url>https://gitlab.pasteur.fr/bia/icy/pom-icy/-/pipelines</url>
    </ciManagement>

    <organization>
        <name>Institut Pasteur</name>
        <url>https://www.pasteur.fr/</url>
    </organization>

    <licenses>
        <license>
            <name>GNU LGPLv3</name>
            <url>https://www.gnu.org/licenses/lgpl-3.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>tmusset</id>
            <name>Thomas Musset</name>
            <url>https://icy.bioimageanalysis.org/author/tmusset/</url>
            <roles>
                <role>lead</role>
                <role>developer</role>
                <role>debugger</role>
                <role>reviewer</role>
                <role>support</role>
                <role>maintainer</role>
            </roles>
        </developer>
    </developers>

    <contributors>
        <contributor>
            <name>Stéphane Dallongeville</name>
            <url>https://icy.bioimageanalysis.org/author/stef/</url>
            <roles>
                <role>founder</role>
            </roles>
        </contributor>
        <contributor>
            <name>Amandine Tournay</name>
            <url>https://icy.bioimageanalysis.org/author/amandine-tournay/</url>
        </contributor>
        <contributor>
            <name>Jean-Yves Tinevez</name>
            <url>https://icy.bioimageanalysis.org/author/tinevez/</url>
        </contributor>
    </contributors>

    <mailingLists>
        <mailingList>
            <name>Icy</name>
            <post>icy.team@pasteur.fr</post>
        </mailingList>
    </mailingLists>

    <properties>
        <!-- Project licence -->
        <license.licenseName>GNU LGPLv3</license.licenseName>
        <license.copyrightOwners>Institut Pasteur</license.copyrightOwners>

        <!-- Project Information -->
        <min.java.version>17</min.java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jdk.version>[${min.java.version},)</jdk.version>

        <!-- SciJava settings -->
        <scijava.jvm.version>${min.java.version}</scijava.jvm.version>
        <scijava.javadoc.url.java>https://javadoc.scijava.org/Java${min.java.version}/</scijava.javadoc.url.java>
        <scijava.javadoc.url.javafx>https://javadoc.scijava.org/JavaFX${min.java.version}/</scijava.javadoc.url.javafx>

        <!-- Maven Plugins version -->
        <enforcer-maven-plugin.version>1.0.0-a.7</enforcer-maven-plugin.version>
        <fr.icy.maven.enforcer-maven-plugin.version>${enforcer-maven-plugin.version}</fr.icy.maven.enforcer-maven-plugin.version>
        <mojo-maven-plugin.version>1.0.0-a.7</mojo-maven-plugin.version>
        <fr.icy.maven.mojo-maven-plugin.version>${mojo-maven-plugin.version}</fr.icy.maven.mojo-maven-plugin.version>

        <!-- Maven plugin properties -->
        <maven-source-plugin.includePom>true</maven-source-plugin.includePom>
        <maven-jar-plugin.includeMavenDescriptor>true</maven-jar-plugin.includeMavenDescriptor>

        <!-- Maven build configuration -->
        <outputDirectory>${project.build.directory}</outputDirectory>
        <stripVersion>true</stripVersion>
        <overWriteIfNewer>true</overWriteIfNewer>
        <overWriteSnapshots>true</overWriteSnapshots>
        <overWriteReleases>true</overWriteReleases>

        <!-- Icy third-party versions -->
        <!-- # JetBrains Annotations -->
        <annotations.version>26.1.0</annotations.version>
        <org.jetbrains.annotations.version>${annotations.version}</org.jetbrains.annotations.version>

        <!-- # EhCache -->
        <ehcache.version>3.12.0</ehcache.version>
        <org.ehcache.ehcache.version>${ehcache.version}</org.ehcache.ehcache.version>

        <!-- # HTTP Components -->
        <httpclient5.version>5.6.1</httpclient5.version>
        <httpclient5-cache.version>${httpclient5.version}</httpclient5-cache.version>
        <httpclient5-fluent.version>${httpclient5.version}</httpclient5-fluent.version>
        <org.apache.httpcomponents.client5.httpclient5.version>${httpclient5.version}</org.apache.httpcomponents.client5.httpclient5.version>
        <org.apache.httpcomponents.client5.httpclient5-cache.version>${httpclient5-cache.version}</org.apache.httpcomponents.client5.httpclient5-cache.version>
        <org.apache.httpcomponents.client5.httpclient5-fluent.version>${httpclient5-fluent.version}</org.apache.httpcomponents.client5.httpclient5-fluent.version>
        <httpcore5.version>5.4.2</httpcore5.version>
        <httpcore5-h2.version>${httpcore5.version}</httpcore5-h2.version>
        <httpcore5-reactive.version>${httpcore5.version}</httpcore5-reactive.version>
        <org.apache.httpcomponents.core5.httpcore5.version>${httpcore5.version}</org.apache.httpcomponents.core5.httpcore5.version>
        <org.apache.httpcomponents.core5.httpcore5-h2.version>${httpcore5-h2.version}</org.apache.httpcomponents.core5.httpcore5-h2.version>
        <org.apache.httpcomponents.core5.httpcore5-reactive.version>${httpcore5-reactive.version}</org.apache.httpcomponents.core5.httpcore5-reactive.version>

        <!-- # JANSI -->
        <jansi.version>2.4.3</jansi.version>
        <org.fusesource.jansi.version>${jansi.version}</org.fusesource.jansi.version>

        <!-- # JAXB -->
        <jaxb-runtime.version>4.0.8</jaxb-runtime.version>
        <org.glassfish.jaxb.jaxb-runtime.version>${jaxb-runtime.version}</org.glassfish.jaxb.jaxb-runtime.version>

        <!-- # JSpecify -->
        <jspecify.version>1.0.0</jspecify.version>
        <org.jspecify.jspecify.version>${jspecify.version}</org.jspecify.jspecify.version>

        <!-- # SwingX -->
        <swingx-all.version>1.6.5-1</swingx-all.version>
        <org.swinglabs.swingx.swingx-all.version>${swingx-all.version}</org.swinglabs.swingx.swingx-all.version>

        <!-- Icy version -->
        <icy.version>3.0.0-a.7</icy.version>
        <fr.icy.icy.version>${icy.version}</fr.icy.icy.version>

        <!-- Icy shared library versions -->
        <!-- # Task -->
        <icy.task.version>1.0.0-a.7</icy.task.version>
        <fr.icy.shared.task>${icy.task.version}</fr.icy.shared.task>

        <!-- # VTK -->
        <vtk.version>9.4.2</vtk.version>
        <org.vtk.vtk.version>${vtk.version}</org.vtk.vtk.version>
        <icy.vtk.version>1.0.0-a.7</icy.vtk.version>
        <fr.icy.shared.vtk.version>${icy.vtk.version}</fr.icy.shared.vtk.version>

        <!-- Icy core extension versions -->
        <!-- # Icy2API -->
        <icy.icy2api.version>1.0.0-a.7</icy.icy2api.version>
        <fr.icy.extensions.icy2-api.version>${icy.icy2api.version}</fr.icy.extensions.icy2-api.version>

        <!-- # Kernel extension -->
        <icy.kernel.version>1.0.0-a.7</icy.kernel.version>
        <fr.icy.extensions.kernel.version>${icy.kernel.version}</fr.icy.extensions.kernel.version>

        <!-- # EzPlug -->
        <icy.ezplug.version>4.0.0-a.7</icy.ezplug.version>
        <fr.icy.extensions.ezplug.version>${icy.ezplug.version}</fr.icy.extensions.ezplug.version>

        <!-- # Protocols -->
        <icy.protocols.version>4.0.0-a.7</icy.protocols.version>
        <fr.icy.extensions.protocols.version>${icy.protocols.version}</fr.icy.extensions.protocols.version>

        <!-- Icy extension versions -->
        <icy.extension.3d-mesh-roi.version>2.0.0-a.5</icy.extension.3d-mesh-roi.version>
        <icy.extension.3d-rotation.version>2.0.0-a.5</icy.extension.3d-rotation.version>
        <icy.extension.3d-spheres-vtk.version>2.0.0-a.5</icy.extension.3d-spheres-vtk.version>
        <icy.extension.active-contours.version>5.0.0-a.5</icy.extension.active-contours.version>
        <icy.extension.angle-descriptor.version>2.0.0-a.5</icy.extension.angle-descriptor.version>
        <icy.extension.angle-helper.version>2.0.0-a.5</icy.extension.angle-helper.version>
        <icy.extension.best-threshold.version>2.0.0-a.5</icy.extension.best-threshold.version>
        <icy.extension.blockvars.version>1.0.0-a.5</icy.extension.blockvars.version>
        <icy.extension.channel-montage.version>3.0.0-a.5</icy.extension.channel-montage.version>
        <icy.extension.color-bar.version>2.0.0-a.5</icy.extension.color-bar.version>
        <icy.extension.color-picker-threshold.version>2.0.0-a.5</icy.extension.color-picker-threshold.version>
        <icy.extension.color-track-processor.version>2.0.0-a.5</icy.extension.color-track-processor.version>
        <icy.extension.connected-components.version>5.0.0-a.5</icy.extension.connected-components.version>
        <icy.extension.convexify.version>3.0.0-a.5</icy.extension.convexify.version>
        <icy.extension.detection-to-roi.version>2.0.0-a.5</icy.extension.detection-to-roi.version>
        <icy.extension.distance-profiler.version>2.0.0-a.5</icy.extension.distance-profiler.version>
        <icy.extension.edge-detection.version>1.0.0-a.5</icy.extension.edge-detection.version>
        <icy.extension.elevation-map.version>3.0.0-a.5</icy.extension.elevation-map.version>
        <icy.extension.emory-jtransforms.version>1.0.0-a.5</icy.extension.emory-jtransforms.version>
        <icy.extension.fill-holes-in-roi.version>2.0.0-a.5</icy.extension.fill-holes-in-roi.version>
        <icy.extension.filter-toolbox.version>5.0.0-a.5</icy.extension.filter-toolbox.version>
        <icy.extension.flanagan.version>2.0.0-a.5</icy.extension.flanagan.version>
        <icy.extension.flying-camera.version>2.0.0-a.5</icy.extension.flying-camera.version>
        <icy.extension.global-visible-persistence.version>2.0.0-a.5</icy.extension.global-visible-persistence.version>
        <icy.extension.graaljs.version>1.0.0-a.5</icy.extension.graaljs.version>
        <icy.extension.hk-means.version>3.0.0-a.5</icy.extension.hk-means.version>
        <icy.extension.image-to-workbook.version>3.0.0-a.1</icy.extension.image-to-workbook.version>
        <icy.extension.imglib2-icy.version>8.0.0-a.3</icy.extension.imglib2-icy.version>
        <icy.extension.intensity-profile.version>2.0.0-a.1</icy.extension.intensity-profile.version>
        <icy.extension.intensity-projection.version>2.0.0-a.2</icy.extension.intensity-projection.version>
        <icy.extension.invert.version>3.0.0-a.2</icy.extension.invert.version>
        <icy.extension.isotropic-wavelet-transform.version>2.0.0-a.1</icy.extension.isotropic-wavelet-transform.version>
        <icy.extension.jama.version>2.0.0-a.5</icy.extension.jama.version>
        <icy.extension.java3d.version>2.0.0-a.5</icy.extension.java3d.version>
        <icy.extension.javacl.version>2.0.0-a.5</icy.extension.javacl.version>
        <icy.extension.jfreechart.version>2.0.0-a.5</icy.extension.jfreechart.version>
        <icy.extension.jmath.version>1.0.0-a.5</icy.extension.jmath.version>
        <icy.extension.jna.version>6.0.0-a.3</icy.extension.jna.version>
        <icy.extension.jep.version>5.0.0-a.5</icy.extension.jep.version>
        <icy.extension.jruby.version>1.0.0-a.5</icy.extension.jruby.version>
        <icy.extension.kmeans-color-quantization.version>2.0.0-a.1</icy.extension.kmeans-color-quantization.version>
        <icy.extension.kymograph-tracker.version>2.0.0-a.1</icy.extension.kymograph-tracker.version>
        <icy.extension.label-extractor.version>2.0.0-a.5</icy.extension.label-extractor.version>
        <icy.extension.linear-programming.version>2.0.0-a.5</icy.extension.linear-programming.version>
        <icy.extension.magnifier.version>4.0.0-a.1</icy.extension.magnifier.version>
        <icy.extension.mask-editor.version>2.0.0-a.1</icy.extension.mask-editor.version>
        <icy.extension.mcib3d-core.version>4.0.0-a.2</icy.extension.mcib3d-core.version>
        <icy.extension.median-filter.version>3.0.0-a.1</icy.extension.median-filter.version>
        <icy.extension.micromanager.version>2.0.0-a.1</icy.extension.micromanager.version>
        <icy.extension.micromanager-block.version>2.0.0-a.1</icy.extension.micromanager-block.version>
        <icy.extension.microscope-remote.version>3.0.0-a.1</icy.extension.microscope-remote.version>
        <icy.extension.montage-2d.version>1.0.0-a.2</icy.extension.montage-2d.version>
        <icy.extension.morphomaths.version>6.0.0-a.5</icy.extension.morphomaths.version>
        <icy.extension.motion-profiler.version>5.0.0-a.3</icy.extension.motion-profiler.version>
        <icy.extension.msd-track-processor.version>2.0.0-a.1</icy.extension.msd-track-processor.version>
        <icy.extension.nherve-image-analysis-toolbox.version>2.0.0-a.1</icy.extension.nherve-image-analysis-toolbox.version>
        <icy.extension.nherve-matrix.version>2.0.0-a.5</icy.extension.nherve-matrix.version>
        <icy.extension.nherve-toolbox.version>2.0.0-a.5</icy.extension.nherve-toolbox.version>
        <icy.extension.ochafik.version>1.0.0-a.5</icy.extension.ochafik.version>
        <icy.extension.opencv.version>5.0.0-a.1</icy.extension.opencv.version>
        <icy.extension.orthoviewer.version>3.0.0-a.2</icy.extension.orthoviewer.version>
        <icy.extension.particle-animation.version>2.0.0-a.1</icy.extension.particle-animation.version>
        <icy.extension.path-intensity-profiler.version>2.0.0-a.1</icy.extension.path-intensity-profiler.version>
        <icy.extension.projection.version>2.0.0-a.1</icy.extension.projection.version>
        <icy.extension.protractor.version>2.0.0-a.1</icy.extension.protractor.version>
        <icy.extension.quickhull.version>2.0.0-a.5</icy.extension.quickhull.version>
        <icy.extension.random-roi-coloring.version>2.0.0-a.1</icy.extension.random-roi-coloring.version>
        <icy.extension.renjin.version>1.0.0-a.5</icy.extension.renjin.version>
        <icy.extension.rescale-roi.version>2.0.0-a.1</icy.extension.rescale-roi.version>
        <icy.extension.ring-roi.version>3.0.0-a.1</icy.extension.ring-roi.version>
        <icy.extension.roi-blocks.version>2.0.0-a.5</icy.extension.roi-blocks.version>
        <icy.extension.roi-inclusion-analysis.version>2.0.0-a.1</icy.extension.roi-inclusion-analysis.version>
        <icy.extension.roi-intensity-evolution.version>3.0.0-a.1</icy.extension.roi-intensity-evolution.version>
        <icy.extension.roi-pool.version>2.0.0-a.5</icy.extension.roi-pool.version>
        <icy.extension.roi-proximity-analysis.version>2.0.0-a.1</icy.extension.roi-proximity-analysis.version>
        <icy.extension.roi-statistics.version>6.0.0-a.3</icy.extension.roi-statistics.version>
        <icy.extension.roi-tagger.version>2.0.0-a.5</icy.extension.roi-tagger.version>
        <icy.extension.roi-to-detection.version>2.0.0-a.2</icy.extension.roi-to-detection.version>
        <icy.extension.roi-to-distance-map.version>4.0.0-a.1</icy.extension.roi-to-distance-map.version>
        <icy.extension.roi-tooltip.version>2.0.0-a.1</icy.extension.roi-tooltip.version>
        <icy.extension.ruler-helper.version>2.0.0-a.5</icy.extension.ruler-helper.version>
        <icy.extension.scale-bar.version>4.0.0-a.2</icy.extension.scale-bar.version>
        <icy.extension.script-manager-core.version>1.0.0-a.6</icy.extension.script-manager-core.version>
        <icy.extension.script-manager-gui.version>1.0.0-a.6</icy.extension.script-manager-gui.version>
        <icy.extension.sequence-blocks.version>3.0.0-a.5</icy.extension.sequence-blocks.version>
        <icy.extension.slic.version>2.0.0-a.1</icy.extension.slic.version>
        <icy.extension.soda-suite.version>2.0.0-a.1</icy.extension.soda-suite.version>
        <icy.extension.spot-detection-utilities.version>2.0.0-a.5</icy.extension.spot-detection-utilities.version>
        <icy.extension.spot-detector.version>2.0.0-a.5</icy.extension.spot-detector.version>
        <icy.extension.spot-detector-block.version>2.0.0-a.1</icy.extension.spot-detector-block.version>
        <icy.extension.spot-tracking.version>4.0.0-a.5</icy.extension.spot-tracking.version>
        <icy.extension.spot-tracking-blocks.version>2.0.0-a.1</icy.extension.spot-tracking-blocks.version>
        <icy.extension.stack-rotation.version>2.0.0-a.1</icy.extension.stack-rotation.version>
        <icy.extension.stereo-3d-vtk-canvas.version>2.0.0-a.1</icy.extension.stereo-3d-vtk-canvas.version>
        <icy.extension.texture-segmentation.version>2.0.0-a.1</icy.extension.texture-segmentation.version>
        <icy.extension.thresholder.version>4.0.0-a.5</icy.extension.thresholder.version>
        <icy.extension.timestamp-overlay.version>2.0.0-a.1</icy.extension.timestamp-overlay.version>
        <icy.extension.track-manager.version>2.0.0-a.5</icy.extension.track-manager.version>
        <icy.extension.track-painter.version>3.0.0-a.1</icy.extension.track-painter.version>
        <icy.extension.track-processor-excel-export.version>2.0.0-a.5</icy.extension.track-processor-excel-export.version>
        <icy.extension.track-processor-filtered-rois.version>2.0.0-a.1</icy.extension.track-processor-filtered-rois.version>
        <icy.extension.track-processor-flow.version>2.0.0-a.1</icy.extension.track-processor-flow.version>
        <icy.extension.track-processor-instant-speed.version>2.0.0-a.1</icy.extension.track-processor-instant-speed.version>
        <icy.extension.track-processor-intensity-profile.version>2.0.0-a.2</icy.extension.track-processor-intensity-profile.version>
        <icy.extension.track-processor-roi-gate.version>2.0.0-a.1</icy.extension.track-processor-roi-gate.version>
        <icy.extension.track-processor-time-clip.version>2.0.0-a.1</icy.extension.track-processor-time-clip.version>
        <icy.extension.tracking-benchmark-generator.version>2.0.0-a.5</icy.extension.tracking-benchmark-generator.version>
        <icy.extension.vecmath.version>2.0.0-a.5</icy.extension.vecmath.version>
        <icy.extension.water-shed-3d.version>2.0.0-a.2</icy.extension.water-shed-3d.version>
        <icy.extension.workbooks.version>4.0.0-a.5</icy.extension.workbooks.version>

        <!-- DO NOT USE -->
        <!-- Old Icy plugin versions -->
        <icy.plugin.big-image-tools.version>3.0.0</icy.plugin.big-image-tools.version>
        <icy.plugin.bunwrap.version>2.0.0</icy.plugin.bunwrap.version>
        <icy.plugin.math-operations.version>3.0.0</icy.plugin.math-operations.version>
        <icy.plugin.math-operations-pp.version>3.0.0</icy.plugin.math-operations-pp.version>
        <icy.plugin.matlab-communicator.version>1.0.5</icy.plugin.matlab-communicator.version>
        <icy.plugin.matlab-exporter.version>2.5.1</icy.plugin.matlab-exporter.version>
        <icy.plugin.matlab-function-caller.version>1.0.0</icy.plugin.matlab-function-caller.version>
        <icy.plugin.matlab-importer.version>2.5.1</icy.plugin.matlab-importer.version>
        <icy.plugin.matlab-io.version>2.5.2</icy.plugin.matlab-io.version>
        <icy.plugin.matlab-x-server.version>3.2.0</icy.plugin.matlab-x-server.version>
        <icy.plugin.mice-profile-tracker.version>8.0.0</icy.plugin.mice-profile-tracker.version>
        <icy.plugin.oshi-core-jdk6.version>3.4.2</icy.plugin.oshi-core-jdk6.version>
        <icy.plugin.rigid-registration.version>1.4.0</icy.plugin.rigid-registration.version>
        <icy.plugin.tensor-flow-manager.version>1.0.0</icy.plugin.tensor-flow-manager.version>
        <icy.plugin.track-processor-intensity-profile-lagache.version>1.0.1</icy.plugin.track-processor-intensity-profile-lagache.version>
        <icy.plugin.video-importer.version>1.1.3</icy.plugin.video-importer.version>
        <icy.plugin.video-recorder.version>1.2.2</icy.plugin.video-recorder.version>
        <icy.plugin.voronoi.version>1.0.0</icy.plugin.voronoi.version>
        <icy.plugin.webcam-capture-example.version>1.0.4</icy.plugin.webcam-capture-example.version>
        <icy.plugin.webcam-capture-library.version>1.0.0</icy.plugin.webcam-capture-library.version>
        <icy.plugin.well-plate-reader.version>3.0.3</icy.plugin.well-plate-reader.version>
        <icy.plugin.workspace-editor.version>1.3.2</icy.plugin.workspace-editor.version>

        <!-- Old Icy plugin-library versions (obsolete) -->
        <icy.plugin-library.apache-commons-collections.version>5.0.0</icy.plugin-library.apache-commons-collections.version>
        <icy.plugin-library.apache-commons-csv.version>2.0.0</icy.plugin-library.apache-commons-csv.version>
        <icy.plugin-library.apache-commons-logging.version>2.0.0</icy.plugin-library.apache-commons-logging.version>
        <icy.plugin-library.apache-httpclient.version>5.0.0</icy.plugin-library.apache-httpclient.version>
        <icy.plugin-library.apache-xmlbeans.version>6.0.0</icy.plugin-library.apache-xmlbeans.version>
        <icy.plugin-library.autocomplete.version>3.0.0</icy.plugin-library.autocomplete.version>
        <icy.plugin-library.bridj.version>1.0.0</icy.plugin-library.bridj.version>
        <icy.plugin-library.clipper.version>7.0.0</icy.plugin-library.clipper.version>
        <icy.plugin-library.clojure.version>2.0.0</icy.plugin-library.clojure.version>
        <icy.plugin-library.docker4icy.version>4.0.0</icy.plugin-library.docker4icy.version>
        <icy.plugin-library.ejml.version>1.0.0</icy.plugin-library.ejml.version>
        <icy.plugin-library.javacpp.version>2.0.0</icy.plugin-library.javacpp.version>
        <icy.plugin-library.jmf.version>3.0.0</icy.plugin-library.jmf.version>
        <icy.plugin-library.joal.version>3.0.0</icy.plugin-library.joal.version>
        <icy.plugin-library.jocl.version>6.0.0</icy.plugin-library.jocl.version>
        <icy.plugin-library.google-flatbuffers.version>2.0.0</icy.plugin-library.google-flatbuffers.version>
        <icy.plugin-library.google-gson.version>3.0.0</icy.plugin-library.google-gson.version>
        <icy.plugin-library.msgpack-core.version>1.0.0</icy.plugin-library.msgpack-core.version>
        <icy.plugin-library.parallel-colt.version>6.0.0</icy.plugin-library.parallel-colt.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <!-- Icy -->
            <dependency>
                <groupId>fr.icy</groupId>
                <artifactId>icy</artifactId>
                <version>${fr.icy.icy.version}</version>
            </dependency>

            <!-- Icy libraries -->
            <!-- # Task -->
            <dependency>
                <groupId>fr.icy.shared</groupId>
                <artifactId>task</artifactId>
                <version>${fr.icy.shared.task}</version>
            </dependency>

            <!-- # VTK (recompiled) -->
            <dependency>
                <groupId>fr.icy.shared</groupId>
                <artifactId>vtk</artifactId>
                <version>${fr.icy.shared.vtk.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.icy.shared</groupId>
                <artifactId>vtk</artifactId>
                <version>${fr.icy.shared.vtk.version}</version>
                <classifier>natives-linux-amd64</classifier>
            </dependency>
            <dependency>
                <groupId>fr.icy.shared</groupId>
                <artifactId>vtk</artifactId>
                <version>${fr.icy.shared.vtk.version}</version>
                <classifier>natives-macos-amd64</classifier>
            </dependency>
            <dependency>
                <groupId>fr.icy.shared</groupId>
                <artifactId>vtk</artifactId>
                <version>${fr.icy.shared.vtk.version}</version>
                <classifier>natives-macos-arm64</classifier>
            </dependency>
            <dependency>
                <groupId>fr.icy.shared</groupId>
                <artifactId>vtk</artifactId>
                <version>${fr.icy.shared.vtk.version}</version>
                <classifier>natives-windows-amd64</classifier>
            </dependency>

            <!-- Icy core extensions -->
            <dependency>
                <groupId>fr.icy.extensions</groupId>
                <artifactId>icy2-api</artifactId>
                <version>${fr.icy.extensions.icy2-api.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.icy.extensions</groupId>
                <artifactId>kernel</artifactId>
                <version>${fr.icy.extensions.kernel.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.icy.extensions</groupId>
                <artifactId>ezplug</artifactId>
                <version>${fr.icy.extensions.ezplug.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.icy.extensions</groupId>
                <artifactId>protocols</artifactId>
                <version>${fr.icy.extensions.protocols.version}</version>
            </dependency>

            <!-- Icy extensions -->

            <!-- Icy third parties -->
            <!-- # JetBrains Annotations -->
            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>annotations</artifactId>
                <version>${org.jetbrains.annotations.version}</version>
            </dependency>

            <!-- # EhCache -->
            <dependency>
                <groupId>org.ehcache</groupId>
                <artifactId>ehcache</artifactId>
                <version>${org.ehcache.ehcache.version}</version>
            </dependency>
            <!-- # JAXB (used by EhCache) -->
            <dependency>
                <groupId>org.glassfish.jaxb</groupId>
                <artifactId>jaxb-runtime</artifactId>
                <version>${org.glassfish.jaxb.jaxb-runtime.version}</version>
            </dependency>

            <!-- # FlatLaf -->
            <dependency>
                <groupId>com.formdev</groupId>
                <artifactId>flatlaf-extras</artifactId>
                <version>${com.formdev.flatlaf.version}</version>
            </dependency>
            <dependency>
                <groupId>com.formdev</groupId>
                <artifactId>flatlaf-swingx</artifactId>
                <version>${com.formdev.flatlaf.version}</version>
            </dependency>

            <!-- # JANSI -->
            <dependency>
                <groupId>org.fusesource.jansi</groupId>
                <artifactId>jansi</artifactId>
                <version>${org.fusesource.jansi.version}</version>
            </dependency>

            <!-- # JSpecify -->
            <dependency>
                <groupId>org.jspecify</groupId>
                <artifactId>jspecify</artifactId>
                <version>${org.jspecify.jspecify.version}</version>
            </dependency>

            <!-- # SwingX -->
            <dependency>
                <groupId>org.swinglabs.swingx</groupId>
                <artifactId>swingx-all</artifactId>
                <version>${org.swinglabs.swingx.swingx-all.version}</version>
            </dependency>

            <!-- Icy extension third parties -->
            <!-- # HttpClient5 / HttpCore5 -->
            <dependency>
                <groupId>org.apache.httpcomponents.client5</groupId>
                <artifactId>httpclient5</artifactId>
                <version>${org.apache.httpcomponents.client5.httpclient5.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents.client5</groupId>
                <artifactId>httpclient5-cache</artifactId>
                <version>${org.apache.httpcomponents.client5.httpclient5-cache.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents.client5</groupId>
                <artifactId>httpclient5-fluent</artifactId>
                <version>${org.apache.httpcomponents.client5.httpclient5-fluent.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents.core5</groupId>
                <artifactId>httpcore5</artifactId>
                <version>${org.apache.httpcomponents.core5.httpcore5.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents.core5</groupId>
                <artifactId>httpcore5-h2</artifactId>
                <version>${org.apache.httpcomponents.core5.httpcore5-h2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents.core5</groupId>
                <artifactId>httpcore5-reactive</artifactId>
                <version>${org.apache.httpcomponents.core5.httpcore5-reactive.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- default build -->
    <build>
        <finalName>${project.artifactId}-${project.version}</finalName>
        <defaultGoal>clean install</defaultGoal>

        <!-- List of Maven plugins for the default build -->
        <pluginManagement>
            <!-- Set the default compilation target to 17 -->
            <plugins>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <source>17</source>
                        <target>17</target>
                        <release>17</release>
                    </configuration>
                    <executions>
                        <execution>
                            <id>default-compile</id>
                            <configuration>
                                <source>17</source>
                                <target>17</target>
                                <release>17</release>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <!-- Enable the multi-release support in jar -->
                <plugin>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${maven-jar-plugin.version}</version>
                    <configuration>
                        <outputDirectory>${outputDirectory}</outputDirectory>
                        <archive>
                            <addMavenDescriptor>${maven-jar-plugin.includeMavenDescriptor}</addMavenDescriptor>
                            <manifestEntries>
                                <Multi-Release>true</Multi-Release>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>

                <!-- Fix for multi-release support -->
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${jacoco-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>jacoco-initialize</id>
                            <goals>
                                <goal>prepare-agent</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>jacoco-site</id>
                            <phase>package</phase>
                            <goals>
                                <goal>report</goal>
                            </goals>
                            <configuration>
                                <!-- Exclude alternate versions for multi-release modules-->
                                <excludes>
                                    <exclude>META-INF/**/*</exclude>
                                </excludes>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>${maven-javadoc-plugin.version}</version>
                    <configuration>
                        <!-- Remove custom tags defined in pom-scijava-base, prevent throwing warning about @implNote -->
                        <tags combine.self="override"/>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <!-- Default profile for kernel-related projects -->
        <!-- Such as 'fr.icy:pom-icy', 'fr.ic:icy', custom maven plugins, recompiled third-parties and libraries -->
        <profile>
            <id>icy-kernel</id>
            <activation>
                <file>
                    <exists>${project.basedir}/.kernel</exists>
                </file>
            </activation>
        </profile>

        <!-- Default profile for non-kernel projects (non-kernel projects are considered as extensions) -->
        <profile>
            <id>icy-extension</id>
            <activation>
                <file>
                    <missing>${project.basedir}/.kernel</missing>
                </file>
            </activation>

            <build>
                <plugins>
                    <!-- Custom enforcer rules for Icy extensions -->
                    <plugin>
                        <artifactId>maven-enforcer-plugin</artifactId>
                        <version>${maven-enforcer-plugin.version}</version>
                        <dependencies>
                            <dependency>
                                <groupId>fr.icy.maven</groupId>
                                <artifactId>enforcer-maven-plugin</artifactId>
                                <version>${fr.icy.maven.enforcer-maven-plugin.version}</version>
                            </dependency>
                        </dependencies>
                        <executions>
                            <execution>
                                <id>icy-enforcer</id>
                                <goals>
                                    <goal>enforce</goal>
                                </goals>
                                <configuration>
                                    <rules>
                                        <validateVersion implementation="fr.icy.maven.plugin.enforcer.ValidateVersion"/>
                                    </rules>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- Custom mojo helper for Icy extensions -->
                    <plugin>
                        <groupId>fr.icy.maven</groupId>
                        <artifactId>mojo-maven-plugin</artifactId>
                        <version>${fr.icy.maven.mojo-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>generate-properties</id>
                                <goals>
                                    <goal>generate-extension-properties</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>install-extension</id>
                                <goals>
                                    <goal>install-extension</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>deploy-extension</id>
                                <goals>
                                    <goal>deploy-extension</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- Populate resources folder -->
                    <plugin>
                        <artifactId>maven-resources-plugin</artifactId>
                        <version>${maven-resources-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>copy-extension-data</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.outputDirectory}/META-INF/data/</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>${project.basedir}</directory>
                                            <includes>
                                                <include>icon.png</include>
                                                <include>icon.svg</include>
                                                <include>CHANGELOG.md</include>
                                                <include>README.md</include>
                                            </includes>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                            <execution>
                                <id>copy-icons-dir</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.outputDirectory}/META-INF/icons/</outputDirectory>
                                    <filters>
                                        <filter>

                                        </filter>
                                    </filters>
                                    <resources>
                                        <resource>
                                            <directory>${project.basedir}/icons/</directory>
                                            <includes>
                                                <include>**/*.svg</include>
                                            </includes>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>

            <!-- Required dependencies for Icy extensions -->
            <dependencies>
                <dependency>
                    <groupId>fr.icy</groupId>
                    <artifactId>icy</artifactId>
                    <version>${fr.icy.icy.version}</version>
                </dependency>
            </dependencies>
        </profile>

        <!-- Enable compiling target for Java 21 compatible projects -->
        <profile>
            <id>multi-release-21</id>
            <activation>
                <jdk>[21,)</jdk>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>java21-compile</id>
                                <phase>compile</phase>
                                <goals>
                                    <goal>compile</goal>
                                </goals>
                                <configuration>
                                    <source>21</source>
                                    <target>21</target>
                                    <release>21</release>
                                    <compileSourceRoots>
                                        <compileSourceRoot>${project.basedir}/src/main/java21</compileSourceRoot>
                                    </compileSourceRoots>
                                    <outputDirectory>${project.build.outputDirectory}/META-INF/versions/21</outputDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- Enable compiling target for Java 25 compatible projects -->
        <profile>
            <id>multi-release-25</id>
            <activation>
                <jdk>[25,)</jdk>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>java25-compile</id>
                                <phase>compile</phase>
                                <goals>
                                    <goal>compile</goal>
                                </goals>
                                <configuration>
                                    <source>25</source>
                                    <target>25</target>
                                    <release>25</release>
                                    <compileSourceRoots>
                                        <compileSourceRoot>${project.basedir}/src/main/java25</compileSourceRoot>
                                    </compileSourceRoots>
                                    <outputDirectory>${project.build.outputDirectory}/META-INF/versions/25</outputDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- Distribution profile -->
        <profile>
            <id>deploy-to-central</id>

            <build>
                <plugins>
                    <!-- Since we publish on Central, default deploy method is not necessary -->
                    <plugin>
                        <artifactId>maven-deploy-plugin</artifactId>
                        <version>${maven-deploy-plugin.version}</version>
                        <inherited>true</inherited>
                        <configuration>
                            <skip>true</skip>
                        </configuration>
                    </plugin>
                    <!-- Source required by Central -->
                    <plugin>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>${maven-source-plugin.version}</version>
                        <configuration>
                            <outputDirectory>${outputDirectory}</outputDirectory>
                            <includePom>${maven-source-plugin.includePom}</includePom>
                        </configuration>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- Javadoc required by Central -->
                    <plugin>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>${maven-javadoc-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- Signing with GPG required by Central -->
                    <!-- If snapshot, skip using -Dgpg.skip=true -->
                    <plugin>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${maven-gpg-plugin.version}</version>
                    </plugin>
                    <!-- Central publishing maven plugin -->
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>${central-publishing-maven-plugin.version}</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                            <autoPublish>false</autoPublish>
                            <forcedOutputDirectory>${project.build.directory}/central-publishing</forcedOutputDirectory>
                        </configuration>
                    </plugin>
                </plugins>
            </build>

            <distributionManagement>
                <repository>
                    <id>central.releases</id>
                    <url>https://central.sonatype.com/api/v1/publisher/upload</url>
                </repository>
                <snapshotRepository>
                    <id>central.snapshots</id>
                    <url>https://central.sonatype.com/repository/maven-snapshots/</url>
                </snapshotRepository>
            </distributionManagement>
        </profile>
    </profiles>

    <repositories>
        <!-- Central first to prevent from searching through every other repository for each dependency (faster) -->
        <repository>
            <id>central</id>
            <name>Maven Central</name>
            <url>https://repo.maven.apache.org/maven2/</url>
        </repository>

        <!-- Every custom / self-hosted artifact repository required by Icy (must be called AFTER Central!) -->
        <repository>
            <id>scijava-public</id>
            <name>SciJava</name>
            <url>https://maven.scijava.org/repository/public/</url>
        </repository>
        <repository>
            <id>ome-repo</id>
            <name>OME repository</name>
            <url>https://artifacts.openmicroscopy.org/artifactory/ome.releases/</url>
        </repository>
        <!--<repository>
            <id>netbeans</id>
            <name>NetBeans</name>
            <url>https://netbeans.apidesign.org/maven2/</url>
        </repository>-->
        <repository>
            <id>jogamp</id>
            <name>JogAmp</name>
            <url>https://jogamp.org/deployment/maven/</url>
        </repository>
    </repositories>
</project>